import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { Shop } from ".prisma/client";
import Navbar from "@/components/Navbar";

interface Props {
  shops?: Shop[];
}

const Index: NextPage<Props> = ({ shops }) => {
  //   const { data: session } = useSession();

  return (
    <div>
      <Head>
        <title>Enfo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="layout">
        <div className="grid w-full gap-5 sm:grid-cols-2 xl:grid-cols-3">
          {shops?.map((shop) => (
            <Link key={shop.id} href={`/shop/${shop.id}`}>
              <a className="w-full bg-white border rounded-md">
                {shop.banner_url && (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={shop.banner_url}
                    alt="banner"
                    className="object-cover w-full h-32"
                  />
                )}
                <div className="p-6">
                  <h3 className="mb-3 font-bold">{shop.name}</h3>
                  <p className="text-justify">{shop.description}</p>
                </div>
              </a>
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Index;

export const getServerSideProps: GetServerSideProps = async () => {
  const shops: Shop[] = await prisma.shop.findMany();
  // console.log(shops);

  return {
    props: { shops },
  };
};
